source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'mandrill-api'
gem 'json'
gem 'mysql2'
gem 'bcrypt'
gem 'sequel'
gem 'sinatra-flash'
gem 'dotenv', '~> 2.0.2'
gem 'bugsnag'
gem 'erubis'
gem 'digest-whirlpool'
gem 'httparty'
gem 'rubyzip'
gem 'nokogiri'

group :test do
  gem 'cucumber'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'launchy'
end
