source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'mandrill-api'
gem 'json'
gem 'mysql2'
gem 'bcrypt'
gem 'sequel'
gem 'sinatra-flash'
gem 'dotenv', '~> 2.0.2'
gem 'bugsnag'
gem 'erubis'
gem 'httparty'
gem 'rubyzip'
gem 'nokogiri'
gem 'rake'
gem 'tzinfo'
gem 'carrierwave'
gem 'carrierwave-sequel'
gem 'mini_magick', '~> 4.2.10'
gem 'sidekiq'
gem 'koala'
