#!/bin/sh

# script/test: Runs the test suite

set -eau

cd "$(dirname "$0")/.."

DATABASE_URL='mysql2://root:@localhost/showdates_test'
BASE_URL='http://localhost:9292/'
SESSION_SECRET='foo'

bundle exec rake
